[project]
name = 'contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.sip013-semi-fungible-token-trait]
path = 'contracts/sip013-semi-fungible-token-trait.clar'
clarity_version = 2
epoch = 2.5

[contracts.sip013-transfer-many-trait]
path = 'contracts/sip013-transfer-many-trait.clar'
clarity_version = 2
epoch = 2.5

[contracts.v3DAO]
path = 'contracts/v3DAO.clar'
clarity_version = 2
epoch = 2.5

[contracts.v3DAOToken]
path = 'contracts/v3DAOToken.clar'
clarity_version = 2
epoch = 2.5

[contracts.v3ProposalVoting]
path = 'contracts/v3ProposalVoting.clar'
clarity_version = 2
epoch = 2.5


[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
