[project]
name = 'contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.FactoryDAO]
path = 'contracts/FactoryDAO.clar'
clarity_version = 2
epoch = 2.5

[contracts.TestFactoryDAO]
path = 'contracts/TestFactoryDAO.clar'
clarity_version = 2
epoch = 2.5

[contracts.v2DAO]
path = 'contracts/v2DAO.clar'
clarity_version = 2
epoch = 2.5

[contracts.v2DAOBuilder]
path = 'contracts/v2DAOBuilder.clar'
clarity_version = 2
epoch = 2.5

[contracts.v2DAOGovernance]
path = 'contracts/v2DAOGovernance.clar'
clarity_version = 2
epoch = 2.5

[contracts.v2DAOToken]
path = 'contracts/v2DAOToken.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
